### ISSUE TITLE
Component wont start

### ISSUE THREAD

**Issue by aspwiz** [groupwhere/homeassistant-tivo#1]
Hi,

I'm using hass.io and have added the tivo.py to the config/custom_components/media_player directory.
Nothing shows in the gui at all but the following is in the home-assistant.log

`
2018-03-06 10:22:58 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up platform tivo
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 79, in async_setup
    None, platform.setup_platform, hass, platform_config,
AttributeError: module 'custom_components.media_player.tivo' has no attribute 'setup_platform'
`

**Comment by groupwhere** [comment]
Sorry you're having trouble.  Can you show the rest of the error from the start (end) of the trace?  Or was that it?  Make sure the config includes:

```
media_player:
  - platform: tivo
    host: 192.168.0.22
    name: Tivo
    port: 31339
    device: 0
```

If you have multiple media_players like me:

```
media_player:
  - platform: samsungtv
    host: 192.168.0.21
  - platform: yamaha
  - platform: tivo
    host: 192.168.0.22
    name: Tivo
    port: 31339
    device: 0
```

**Comment by aspwiz** [comment]
Hi.  How can I find more error info?  Sorry really new to hass but learn extremely fast. 

My config includes exactly the first one you posted but with IP.  Its not throwing any config file errors.  

Help me get you more info...  Is there a more verbose logging switch or flag?

**Comment by aspwiz** [comment]
Just for clarity,  the GUI itself loads fine but no switches or remotes show up.  That error was found in home-assistant.log

**Comment by groupwhere** [comment]
Errors for python show in reverse order with the initial error at the bottom.  Was that the last of it?

**Comment by aspwiz** [comment]
I'll reboot the pi just in case and then paste the whole file...  Bear with
me

**Comment by aspwiz** [comment]
Hmmm..... there is some auto detection of a blu ray player which is also a media player.... the device itself is returning bad xml which might be to do with.  I'm gonna take it off the network and redo all this.  Give me 10 minutes

**Comment by aspwiz** [comment]
Ok, here is my config:
```
media_player:
  - platform: tivo
    host: 192.168.0.21
    name: Tivo
    port: 31339
    device: 0
```
and here is the full home-assistant.log file, it is pretty short.  I have no idea where that ip address is coming from in the very last line as it's not even in my subnet.

```
2018-03-06 16:57:41 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=14 from 2018-03-06 16:49:25.426445)
2018-03-06 16:57:48 ERROR (SyncWorker_5) [custom_components.media_player.tivo] Connecting to Tivo...
2018-03-06 16:57:48 ERROR (SyncWorker_5) [custom_components.media_player.tivo] Sending request: ' 
'
2018-03-06 16:57:48 ERROR (SyncWorker_5) [custom_components.media_player.tivo] Received Tivo data: 'b'CH_STATUS 0101 LOCAL\r''
2018-03-06 16:57:48 ERROR (SyncWorker_5) [custom_components.media_player.tivo] Disconnecting from Tivo...
2018-03-06 16:57:48 ERROR (SyncWorker_5) [custom_components.media_player.tivo] Channel: 0101
2018-03-06 16:57:48 ERROR (SyncWorker_5) [custom_components.media_player.tivo] Status:  LOCAL
2018-03-06 16:58:08 ERROR (MainThread) [homeassistant.core] Timer got out of sync. Resetting
2018-03-06 16:58:20 WARNING (SyncWorker_4) [netdisco.ssdp] Error fetching description at http://192.168.1.250:49152/description.xml
```

I hope this is a little more helpful

**Comment by groupwhere** [comment]
I don't know where that netdisco ip is coming from unless it was a hard-coded default, perhaps.  But, it looks like the connection to Tivo was successful, returning that it is currently on channel 101.  The fact that they are showing as errors was only because that was the logger I selected to ensure that it would get logged.  There is no real error with the tivo component here.  If your bluray player cannot get an ip address from the lan or wifi, it may have selected that ip.  Or, it was valid when you had another router or something.

**Comment by aspwiz** [comment]
Ok, since removing my blu ray from the network, I now have a tivo control showing on the hass homepage - yay!!

I'll  have a play around but let me know what you are working on

**Comment by groupwhere** [comment]
Not much during the week.  I spent time trying to make special channel buttons but backed out from that in favor of the default setup.  I am not sure what is next but it is possible to remotely navigate menus, search, etc.  I really don't know the value of that without having eyes on the TV but we shall see.

**Comment by aspwiz** [comment]
Ok, I'll try and get the power on/off going for now 👍

**Comment by groupwhere** [comment]
I don't think the protocol supports that, unfortunately.  I don't ever turn mine off anyway.  You might be able to send the required keystrokes to put it in standby.  But, I am not sure how you would revive it if you could.

Closing this issue for now.  We can continue the discussion on the homeassistant discord.

**Comment by aspwiz** [comment]
well, I've been messing around with telnet before i found home assistant and I can confirm that sending IRCODE STANDBY works to power off at least..... I know there is a useful list of commands somewhere which I'll try and dig out for you

**Comment by groupwhere** [comment]
The protocol document is linked in the readme.

**Comment by aspwiz** [comment]
Yeah thanks, there was another somewhere that included the standby stuff, I'll see if i can find it again.

With regards to turning on / off I can confirm 100% that "IRCODE STANDBY" is working.  If you send it once, the box will standby after 30 seconds - exactly the same as pressing it in your remote.  If you send the command twice it immediately turns off.  You can send the same command to wake up the box.
I presume the box on/off state would be easy since there would be no channel status returned.

I'm just trying to help and im already in over my head haha

**Comment by groupwhere** [comment]
I found that in my list from wherever as well.  I didn't test it.  But, if the box can be awoken with that, then it is useful.  I can play with it tonight.

**Comment by groupwhere** [comment]
Added on/off to code - untested.

**Comment by aspwiz** [comment]
Got it..... I'll try it.  is this the right config format for two tivo boxes?
```
media_player:
  - platform: tivo
    host: 192.168.0.21
    name: Tivo1
    port: 31339
    device: 0
  - platform: tivo
    host: 192.168.0.10
    name: Tivo2
    port: 31339
    device: 1
```

**Comment by groupwhere** [comment]
I am not sure since I only have one plus some satellites.  Curious whether that works but it looks right.

**Comment by aspwiz** [comment]
Yeah it works fine on device 1....  However,  device 0 doesn't show channel but instead "no title".  Strangely,  device 0 forward and back buttons result in fast forward and rewind lol.  Whereas they change channel up and down on device 1.  Regular channels (not recordings)  are on both boxes.   Power on off works on both.  Hope this helps.  
![screenshot_20180306-200018](https://user-images.githubusercontent.com/37105157/37055807-98e6e5e2-217a-11e8-8ac0-427c5badd2e1.png)

**Comment by groupwhere** [comment]
That's great news (power).  Made another commit.  It was doing fwd/rev because it didn't know it was in tv mode since the initial update failed (type none).  This is an inexact science at this point.

**Comment by aspwiz** [comment]
Well its going well so far and at least you know rewind,  etc will work
when added lol.

I'll update tomorrow and test both boxes.

Cheers
