### ISSUE TITLE
What can we do about this ????

### ISSUE THREAD

**Issue by RPaulsson** [groupwhere/homeassistant-tivo#10]
Log Details (WARNING)
Mon Mar 04 2019 08:26:16 GMT+0100 (centraleuropeisk normaltid)
Integrations need to be in their own folder. Change media_player/tivo.py to tivo/media_player.py. This will stop working soon.

**Comment by groupwhere** [comment]
I just pushed an update.  You may want to git update.  Or, you can:
1. cd to your custom_components folder
2. mkdir tivo
3. mv media_player/tivo.py tivo/media_player.py

**Comment by groupwhere** [comment]
The latest versions of the code fixes this issue, which was a platform change/upgrade.
