### ISSUE TITLE
zap2it not sending information

### ISSUE THREAD

**Issue by garnern2** [groupwhere/homeassistant-tivo#14]
The component is working pretty well in that I can control the TiVo. However, the zap2it portion is not sending program information to the media player card, nor is the channel information complete I get Ch. 3 None: None even if it is on Ch. 3-1 Nightly News. This isn't a huge deal, but I'm curious if there is a simple fix.

**Comment by RFC1920** [comment]
I'm sure I never accounted for the sub-channels.  But, if it goes up and down one sub channel at a time it should work.  The only thing I can suggest first off is to verify that the channel plan selected in your subscription matches what you're doing.  I assume this is OTA?

**Comment by garnern2** [comment]
That's correct...it is OTA. The channels do change. I'm not sure why the zap2it information isn't showing...unless that's the reason (for example, zap2it expects 3-1 or 3.1, not just 3).

**Comment by jcollas** [comment]
It looks like the TiVo returns '3-1' and zap2it shows '3.1'.  Probably an easy fix to just substitute '-' with '.'

**Comment by garnern2** [comment]
Not sure how to go about that but I'd be glad to make the change.

**Comment by jcollas** [comment]
From inspecting the code, you need to change this line (284) to add the replace part.

This needs to be in your config directory, in the file custom_components/tivo/media_player.py

Change the line as specified below, and restart HA.  If this works for you, please let me know, and I’ll submit a bug fix.

Juan


@@ -281,7 +281,7 @@ class TivoDevice(MediaPlayerDevice):
                     self._current["image"] = "https://tvlistings.zap2it.com/assets/images/noImage165x220.jpg"
 
                 if self.usezap:
-                    ch  = str(self._channels.get(words[1]))
+                    ch  = str(self._channels.get(words[1].replace('.', '-')))
                     self._current["channel"] = ch
                     num = str(words[1])
                     num = num.lstrip("0")

**Comment by jcollas** [comment]
Oh hell.  I screwed up the fix.  The line should look like

ch  = str(self._channels.get(words[1].replace('-', '.'))) 

(We need to take the TiVo's '3-1' and change it to zap2it's '3.1' to look up the channel information)

**Comment by garnern2** [comment]
`                if self.usezap:
                    ch = str(self._channels.get(words[1].replace('-', '.')))
                    self._current["channel"] = ch
                    num = str(words[1])
                    num = num.lstrip("0")
                    ti  = str(self._titles.get(words[1]))
                    if self.debug:
                        _LOGGER.warning("Channel:  %s", num)
                        _LOGGER.warning("Callsign: %s", ch)
                        _LOGGER.warning("Title:    %s", ti)`

This is what I have now. I am experiencing the same behavior. Only a whole number, and None: None.

**Comment by garnern2** [comment]
Well crap. This starting at line 283: 

                if self.usezap:
                    ch = str(self._channels.get(words[1].replace('-', '.')))
                    self._current["channel"] = ch
                    num = str(words[1])
                    num = num.lstrip("0")
                    ti  = str(self._titles.get(words[1]))
                    if self.debug:
                        _LOGGER.warning("Channel:  %s", num)
                        _LOGGER.warning("Callsign: %s", ch)
                        _LOGGER.warning("Title:    %s", ti)

**Comment by jcollas** [comment]
I put the fix on the wrong line.  The replace should be on the line

ti = str(self._titles.get(words[1].replace(‘-‘, ‘.’))

The ch is the channel, you want to leave that alone (remove the replace(…)).  It’s the title we care about.

Apologies,

Juan

**Comment by jcollas** [comment]
If the title shows up, you'll have to make the same change on the image a few lines down.  If this works for you, let me know so I can submit a proper fix.

**Comment by garnern2** [comment]
Should it not be:

ti = str(self._titles.get(words[1].replace(‘-‘, ‘.’))) (three closed parentheses)

**Comment by jcollas** [comment]
Of course you're correct.  Yikes.

**Comment by garnern2** [comment]
When I run hassio ha check, I get:

SyntaxError: invalid character in identifier
Fatal error while loading config: invalid character in identifier (media_player.py, line 288)
Failed config
  General Errors: 
    - invalid character in identifier (media_player.py, line 288)

Successful config (partial)

**Comment by garnern2** [comment]
Nevermind. I fixed that. I'm restarting and we will see what happens.

**Comment by garnern2** [comment]
This doesn't work. In the media-control card, I still see: Ch. 3 None: None

**Comment by jcollas** [comment]
Ok.  I'll do a little more digging tonight.  Do you have HACS installed?

**Comment by garnern2** [comment]
I do not have it installed. Not familiar with it.

**Comment by jcollas** [comment]
I checked the zap2it feed, the data coming back looks like the code we tweaked should have fixed it.  Are your zap2it account settings returning the OTA feed instead of a cable feed?

**Comment by garnern2** [comment]
I'm assuming they are...but all I'm seeing is Ch. 3 None: None (I am not seeing 3-1 or 3.1)...

**Comment by jcollas** [comment]
Did you log into zap2it.com and choose the appropriate feed for your zip code, etc?   The change we made should show you a proper title if you've chosen the appropriate feed on the zap2it website.  The image and channel should still be broken.

**Comment by garnern2** [comment]
Yes I did. All I get is None: None

**Comment by garnern2** [comment]
Here's what I have:

                if self.usezap:
                    ch = str(self._channels.get(words[1]))
                    self._current["channel"] = ch
                    num = str(words[1])
                    num = num.lstrip("0")
                    ti = str(self._titles.get(words[1].replace('-', '.')))
                    if self.debug:
                        _LOGGER.warning("Channel:  %s", num)
                        _LOGGER.warning("Callsign: %s", ch)
                        _LOGGER.warning("Title:    %s", ti)

**Comment by garnern2** [comment]
I also created a new zap2it account and tried that. No luck.

**Comment by garnern2** [comment]
I think I found the issue. Fingers crossed...

**Comment by garnern2** [comment]
I left out a space after "ch" and after "ti." I fixed that, and here's what I have now:

                if self.usezap:
                    ch  = str(self._channels.get(words[1]))
                    self._current["channel"] = ch
                    num = str(words[1])
                    num = num.lstrip("0")
                    ti  = str(self._titles.get(words[1].replace('-', '.')))
                    if self.debug:
                        _LOGGER.warning("Channel:  %s", num)
                        _LOGGER.warning("Callsign: %s", ch)
                        _LOGGER.warning("Title:    %s", ti)

This unfortunately does not fix the issue.

**Comment by garnern2** [comment]
Any other ideas? This is the most help I've ever received on GitHub, and it's very appreciated!

**Comment by jcollas** [comment]
Lol.  I was just thinking about what to do next here.  I don't have an OTA TiVo setup, so if you want to work with me to debug, you'll need the telnet command on your computer, and here's a link for using the remote interface:  https://www.tivocommunity.com/community/index.php?threads/tivo-ui-control-via-telnet-no-hacking-required.392385/

What I need is to see what the CH_STATUS for a channel looks like, for one of the '.' channels.  With that, I can figure out why my fix doesn't work.

**Comment by garnern2** [comment]
This is interesting! I think this will help someone with expertise in python figure it out but I'm not familiar with out to do this particular thing...

The channel is reported as 0003 0001 (this is channel 3.1)

**Comment by jcollas** [comment]
Wow, I didn't expect that.  So you're saying you see:

CH_STATUS 0003 0001 LOCAL

?

**Comment by garnern2** [comment]
That's correct.

**Comment by jcollas** [comment]
Ok, I have a fix:  Copy this file (media_player.py) into your custom_components/tivo directory and restart.

https://raw.githubusercontent.com/jcollas/homeassistant-tivo/master/custom_components/tivo/media_player.py

**Comment by garnern2** [comment]
This fixed the channel issue. I now see 3.1, 3.2 and so on. I still see None: None for the other information.

**Comment by jcollas** [comment]
I checked in a fix which zero-fills the subchannel so we can find the zap2it data.  Just copy the media_player.py file again (https://raw.githubusercontent.com/jcollas/homeassistant-tivo/master/custom_components/tivo/media_player.py)

**Comment by garnern2** [comment]
By Juan I think you’ve got it! I will test this extensively the next few days and update if there are any issues. Leaving open for now, but will close on 7/1. You’re the man!

**Comment by jcollas** [comment]
Our long national nightmare is at an end, then.  FYI, the TiVo telnet interface isn’t all that great.  It occasionally goes deaf, and certainly doesn’t work if you’re on the guide and several other edge cases.  I’ve looked into the alternative APIs supported by TiVo, but they don’t give us more robust support.   Enjoy!

**Comment by garnern2** [comment]
Closed! Thanks so much for the fix.
