### ISSUE TITLE
Channel Lookup

### ISSUE THREAD

**Issue by aspwiz** [groupwhere/homeassistant-tivo#2]
Hi,

Sorry I don't know how to collaborate here without opening an issue so sorry if this isn't the right way.  I cant upload files so I'm attaching this lookup table / array to get to channel names from channel numbers. It is a complete up to date list and I've stripped problem ascii characters so it's good to go.

This gives you the option of showing the actual channel name along with the number, if you want that of course.

Hope it helps.

[channelLookup.py.txt](https://github.com/groupwhere/homeassistant-tivo/files/1788301/channelLookup.py.txt)

**Comment by groupwhere** [comment]
If that is a standard, available format then perhaps something like that could be integrated.  Zap2IT used to be free but the only one I know of for consistent guide info is Schedules Direct.  However, perhaps I could add something to use a local file if present for this somewhat static info (channels only).

**Comment by groupwhere** [comment]
Looks like Zap2iT is again available.  Overkill but workable, at least for the US and perhaps Canada.

**Comment by aspwiz** [comment]
Its ripped right out of their official channel list PDF.  Maybe you could get to it progmattically in future :)

**Comment by groupwhere** [comment]
Working on it ;)

**Comment by groupwhere** [comment]
Lookup of data from zap2it has been added.  This may not apply to anyone but the US and Canada.  There are other services but I have yet to find one that was free.  Anyway, with zap2it, we can get the channel call sign and program name.
