### ISSUE TITLE
New code for sub channels breaks cable zap2it data

### ISSUE THREAD

**Issue by va-lemon** [groupwhere/homeassistant-tivo#20]
After upgrading to v0.3.0, HA stopped getting Channel Call Sign, Program Title and Thumbnail for cable channels. The zap2it functions store cable channel numbers as 4 digits padded with zeros (e.g. 0553, 1921).

The updated code in set_status is using zap_ch stripped of leading zeros to look up the Call Sign (ch) and Program Title (ti) in the _channels array. This will not work as zap_ch = 553 when it should be 0553. For now, I've added filler 0s to zap_ch to fix this.
```
                if self.usezap:
                    zap_ch = channel.replace('-', '.')
                    zap_ch = zap_ch.zfill(4)
                    ch  = str(self._channels.get(zap_ch))
                    self._current["channel"] = ch
                    num = str(zap_ch)
                    num = num.lstrip("0")
                    ti  = str(self._titles.get(zap_ch))
```
I don't have sub channels on my cable service so I can't test if this breaks sub channel functionality. Also not sure why the channel lookup variable is being stripped of leading zeros when performing the lookup against the _channel array.

**Comment by jcollas** [comment]
Good catch.  This also breaks for me on channels less than 1000, which I rarely check.

**Comment by groupwhere** [comment]
Juan was able to patch this issue, so I'm closing this.
