### ISSUE TITLE
Not working on HA 0.88.1

### ISSUE THREAD

**Issue by RPaulsson** [groupwhere/homeassistant-tivo#9]
This custom_components stop working on HA 0.88.1

**Comment by groupwhere** [comment]
Thanks, I am running 0.84.2 currently and am not sure when I will get updated.

**Comment by groupwhere** [comment]
See the new branch at https://github.com/groupwhere/homeassistant-tivo/tree/0.88.1 to fix this problem.  Worked for me on 0.88.2.  Sorry for the delay.

**Comment by RPaulsson** [comment]
Thank you its working perfect now.

**Comment by groupwhere** [comment]
Excellent!  Thanks for getting back to me.
